# Use a native, dark-themed, stable theme
theme: jekyll-theme-slate

# Site configuration
title: "IHZAQ | Engineering & Code"
author: "Haziq Zamri"
description: "Electrical & Electronics Engineering Student @ UTP"

# Plugins (Keep it simple)
plugins:
  - jekyll-seo-tag
