# Use the Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes"

# Site configuration
title: "IHZAQ | Engineering & Code"
author: "Haziq Zamri"
description: "Electrical & Electronics Engineering Student @ UTP"

# Enable Dark Mode (Minimal Mistakes has this natively!)
minimal_mistakes_skin: "dark" 

# Other settings
show_downloads: false
